Agrega ejecucion con docker.
jokoframework/joko_backend_starter_kit pull request #27
Opened 2020-08-03 00:00 UTC by jorge683

-Se agregaron los archivos con las configuraciones necesarias para la
ejecucion con docker.
-Se ajusto el archivo RUN.md segun la nueva implementacion.

2020-08-17 13:05 UTC, alefq requested changes
Excelente el resultado Jorge, funcionó de una la ejecución. 
Sólo dejo algunos comentarios para revisar la ortografía. 

:+1:  Buen trabajo.

2020-08-17 13:05 UTC, alefq commented on RUN.md
> +## Ejecución Rapida
Rápida lleva tilde

2020-08-17 13:05 UTC, alefq commented on RUN.md
> +de instalacion mas abajo) entonces se puede proceder a empaquetar el proyecto (Ej: `mvn package`) y luego:
"más" lleva tilde

2020-08-17 13:05 UTC, alefq commented on RUN.md
> +La forma mas simple de levantar el proyecto es con la utilización de Docker, ejecutando
"más" con tilde

2020-08-18 21:29 UTC, jorge683 commented
Gracias Ale. Todo listo!

2020-08-18 22:09 UTC, alefq approved these changes

2020-08-18 22:09 UTC, merged